### ISSUE TITLE
Share the file MMACT_OPENPOSE_COCO.tar.gz

### ISSUE THREAD

**Issue by stackoverflowwwww** [mduhme/mmargcn#3]
Could you please share the file MMACT_OPENPOSE_COCO.tar.gz

**Comment by raphaelmemmesheimer** [comment]
YOu can find them here: https://agas.uni-koblenz.de/fusion-gcn/MMACT_OPENPOSE_COCO.tar.gz

**Comment by stackoverflowwwww** [comment]
Thanks!!!
